# docker-compose.yml for echofish dev environment
# adjust ports 80 and 3306 if already in use on your system
version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-web
    container_name: echofish-web
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./php-timezone.ini:/usr/local/etc/php/conf.d/php-timezone.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  db:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-db
    container_name: echofish-db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "127.0.0.1:3306:3306"
#    volumes:
#      - ./database:/var/lib/mysql
